export const CHANGE_TASK_NAME =			'CHANGE_TASK_NAME';
export const ADD_SUBMITTED_TASK =		'ADD_SUBMITTED_TASK';
export const CHANGE_TASK_STATUS =		'CHANGE_TASK_STATUS';
export const ACTIVATE_EDIT_MODE =		'ACTIVATE_EDIT_MODE';
export const REMOVE_TASK_FROM_LIST =	'REMOVE_TASK_FROM_LIST';